// JavaScript Document
$(document).ready(function(){
    $('.anti_p').hover(function(){
                $(this).addClass('active');
		$('.sub_navigation').show();	
	}).mouseleave(function(){
                $(this).removeClass('active');
		$('.sub_navigation').hide();		
	});
        $('.sub_navigation').mouseover(function(){
                $('.anti_p').addClass('active');
		$(this).show();	
	}).mouseleave(function(){
                $('.anti_p').removeClass('active');
		$(this).hide();		
	});
		
    $('.anti_p1').hover(function(){
                $(this).addClass('active');
		$('.sub_navigation1').show();	
	}).mouseleave(function(){
                $(this).removeClass('active');
		$('.sub_navigation1').hide();		
	});
        $('.sub_navigation1').mouseover(function(){
                $('.anti_p1').addClass('active');
		$(this).show();	
	}).mouseleave(function(){
                $('.anti_p1').removeClass('active');
		$(this).hide();		
	});
	
	 $('.anti_p2').hover(function(){
                $(this).addClass('active');
		$('.sub_navigation2').show();	
	}).mouseleave(function(){
                $(this).removeClass('active');
		$('.sub_navigation2').hide();		
	});
        $('.sub_navigation2').mouseover(function(){
                $('.anti_p2').addClass('active');
		$(this).show();	
	}).mouseleave(function(){
                $('.anti_p2').removeClass('active');
		$(this).hide();		
	});
	
	 $('.anti_p3').hover(function(){
                $(this).addClass('active');
		$('.sub_navigation3').show();	
	}).mouseleave(function(){
                $(this).removeClass('active');
		$('.sub_navigation3').hide();		
	});
        $('.sub_navigation3').mouseover(function(){
                $('.anti_p3').addClass('active');
		$(this).show();	
	}).mouseleave(function(){
                $('.anti_p3').removeClass('active');
		$(this).hide();		
	});
        
 	 $('.anti_p4').hover(function(){
                $(this).addClass('active');
		$('.sub_navigation4').show();	
	}).mouseleave(function(){
                $(this).removeClass('active');
		$('.sub_navigation4').hide();		
	});
        $('.sub_navigation4').mouseover(function(){
                $('.anti_p4').addClass('active');
		$(this).show();	
	}).mouseleave(function(){
                $('.anti_p4').removeClass('active');
		$(this).hide();		
	});
	
	 $('.anti_p5').hover(function(){
                $(this).addClass('active');
		$('.sub_navigation5').show();	
	}).mouseleave(function(){
                $(this).removeClass('active');
		$('.sub_navigation5').hide();		
	});
        $('.sub_navigation5').mouseover(function(){
                $('.anti_p5').addClass('active');
		$(this).show();	
	}).mouseleave(function(){
                $('.anti_p5').removeClass('active');
		$(this).hide();		
	});	
	
	$('.anti_p6').hover(function(){
                $(this).addClass('active');
		$('.sub_navigation6').show();	
	}).mouseleave(function(){
                $(this).removeClass('active');
		$('.sub_navigation6').hide();		
	});
        $('.sub_navigation6').mouseover(function(){
                $('.anti_p6').addClass('active');
		$(this).show();	
	}).mouseleave(function(){
                $('.anti_p6').removeClass('active');
		$(this).hide();		
	});	
})